### ISSUE TITLE
State when alarm starts?

### ISSUE THREAD

**Issue by dennisbrouwer91** [AaronDavidSchneider/SonosAlarm#14]
Hi,

Thanks so much for the great work, this really helps with integrating our alarms in Home-Assistant. One question i had : Is there an easy way to detect when the alarms starts (to go off). I know the switch state in Hass is either on or off (based on the setting in the Sonos app), but how can you detect if the alarm started sounding?

Regards,
Dennis

**Comment by AaronDavidSchneider** [comment]
Hi, 
thanks for your feedback. There is an attribute that holds the time of the alarm. Also: The alarm should turn off, when it starts?! But I am not sure about that.

**Comment by dennisbrouwer91** [comment]
Well, the time is indeed there, but what is it's only for weekdays for example? If i then detect time and do "stuff" when it's that time, it might also do that in the weekend. Maybe it's an idea to add an attribute that shows if this alarm is effective for "today" or something?

**Comment by AaronDavidSchneider** [comment]
I could add an attribute that is true when the alarm is scheduled for today and false else?
This can be easily achieved with https://docs.python-soco.com/en/latest/api/soco.alarms.html#soco.alarms.is_valid_recurrence

Would that help?

**Comment by dennisbrouwer91** [comment]
That would help A LOT! If that attribute is there i can start using it in Node-Red to trigger some stuff when the alarm goes off :)
