### ISSUE TITLE
SONOS discovery failed over multiple local networks

### ISSUE THREAD

**Issue by Schmandre** [AaronDavidSchneider/SonosAlarm#19]
Hello,

unfortunately I have a little problem adding my SONOS speaker with the alarm integration. I have two different local networks (192.168.0.0/24 LAN including HomeAssistant and 10.13.37.0/24 for WLAN). Since the SONOS Speaker is in my WLAN, I had to include the device in the "configuration.yaml" per IP for the "normal" SONOS configuration. (See: https://www.home-assistant.io/integrations/sonos/#advanced-use). Unfortunately, due to the network components used, it is not possible to operate two identical networks via WLAN / LAN, so this was the only option. This works as far as error-free. Unfortunately, however, I can not set up the SONOS_ALARM integration via ha integrations, because the LAN can not find the SONOS speaker in the WLAN network. 

Is there also a possibility, as with the normal SONOS integration, to make the configuration manually? Or maybe tell me how to hard code the ip into the script? :)

Best regards
Schmandre

**Comment by AaronDavidSchneider** [comment]
Hi,

I think this should be possible. We would need to build the function 
```
async def async_setup_platform(hass, config, async_add_entities, discovery_info=None):
```

I would be happy to help you, if you like to try it.

EDIT: This was the wrong idea :D

**Comment by Schmandre** [comment]
Hey,

sure I can try that out. I would only have to know what I need to change and I test the whole thing with you :)

**Comment by AaronDavidSchneider** [comment]
So I took a look into the code again and saw that my answer above was nonsense. 

Could you just try in your configuration.yaml:

```yaml
sonos_alarm:
   switch:
      hosts:
        - 192.168.178.22
        - 192.168.178.29
        - 192.168.178.24
```

With whatever hosts you have?

I think this should in principle still work :D

**Comment by Schmandre** [comment]
I have adapted the configuration.yaml and added the IP of the SONOS Bookshelf Speaker. The config looks like this

```yaml
sonos_alarm:
   switch:
      hosts:
        - 10.13.37.58
```
The IP is the same as for the "normal" SONOS integration. In the overview, I now get the SONOS "Alarm" integration displayed,

![chrome_cPmse305Sb](https://user-images.githubusercontent.com/47451170/114708104-41eae600-9d2b-11eb-9a7a-871d6d1fdc54.png)

 but unfortunately without a device. When I search for "switch" in Lovelace, I unfortunately don't find a loudspeaker or alarm id either. 

![chrome_kWtR3hUm5H](https://user-images.githubusercontent.com/47451170/114708323-7d85b000-9d2b-11eb-83d2-3f80e7687808.png)

Is there anything that needs to be set on the speaker so that it can be managed via the integration, or is there still a small config problem here?

Maybe I missed something? Or is there any other way to get the alert id?

Thank you for your help

**Comment by AaronDavidSchneider** [comment]
Well it certainly works in my case using configuration.yaml:
![Bildschirmfoto 2021-04-14 um 15 40 48](https://user-images.githubusercontent.com/7556347/114719884-cba0b080-9d37-11eb-9e02-9a014d34f3e7.png)

I suppose that in your case one of the following errors occurs:
1. wrong ip of the speaker
2. no alarm set in the speaker

Other than that: The setup step of sonos_alarm is basically copied from the core Sonos integration. I don't know if there has been made any changes to it. You could compare the [`async def async_setup_entry(hass, config_entry, async_add_entities):`](https://github.com/AaronDavidSchneider/SonosAlarm/blob/master/custom_components/sonos_alarm/switch.py#L42) with the one in https://github.com/home-assistant/core/blob/dev/homeassistant/components/sonos/media_player.py and look for differences.

But I doubt that this is the reason.

**Comment by Schmandre** [comment]
Thanks for the reply. I double checked that. IP and alarms are correctly set. The "normal" SONOS Integration still find the speaker and can play music over this ip :(

![WhatsApp Image 2021-04-14 at 19 14 30](https://user-images.githubusercontent.com/47451170/114751707-c3f00480-9d55-11eb-9e25-a9bceae77d99.jpeg)


But now I am completely confused. Is it possible that the IKEA SYMFONISK (SONOS) speakers are not supported? I have completely changed the network so that the WLAN is now in the same network range as HomeAssistant (192.168.0.0/24) HomeAssistant => .120 and speakers => .130.
However, the device still cannot be added.... 

Do you have any other ideas?

This is the output of the log
```
2021-04-14 19:06:14 DEBUG (Thread-9) [pysonos.discovery] Sending discovery packets on 192.168.0.120
2021-04-14 19:06:14 DEBUG (Thread-9) [pysonos.discovery] Sending discovery packets on 172.17.0.1
2021-04-14 19:06:14 DEBUG (Thread-9) [pysonos.discovery] Sending discovery packets on 10.42.0.0
```

Is there perhaps a way to work without pysonos.discovery, or to specify the IP here as well?

**Comment by AaronDavidSchneider** [comment]
No this has nothing todo with the ikea logo. I also have a IKEA speaker and as I said it works in my case (using the configuration.yaml and also using discovery).

It's confusing. Could you make the diff of the two files that I mentioned above and report back the differences? Maybe we see what we are missing in your case.

Also: just so that we dont overdo this. Please consider to remove Sonos alarm completely and readd it.

Good luck!

**Comment by Schmandre** [comment]
Thank you again for the fast reply. I just activated the debug loggin and see, that the default sonos integration send and recieve properly. 

```
2021-04-14 20:31:14 DEBUG (SyncWorker_1) [pysonos.services] Received {'CONTENT-LENGTH': '490', 'CONTENT-TYPE': 'text/xml; charset="utf-8"', 'EXT': '', 'Server': 'Linux UPnP/1.0 Sonos/62.1-86220 (ZPS21)', 'Connection': 'close'}, <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetPositionInfoResponse xmlns:u="urn:schemas-upnp-org:service:AVTransport:1"><Track>0</Track><TrackDuration>0:00:00</TrackDuration><TrackMetaData></TrackMetaData><TrackURI></TrackURI><RelTime>0:00:00</RelTime><AbsTime>NOT_IMPLEMENTED</AbsTime><RelCount>2147483647</RelCount><AbsCount>2147483647</AbsCount></u:GetPositionInfoResponse></s:Body></s:Envelope>
2021-04-14 20:31:14 DEBUG (SyncWorker_1) [pysonos.services] Received status 200 from 192.168.0.154
2021-04-14 20:31:14 DEBUG (SyncWorker_1) [pysonos.services] Sending GetPositionInfo [('InstanceID', 0), ('Channel', 'Master')] to 192.168.0.154
2021-04-14 20:31:14 DEBUG (SyncWorker_1) [pysonos.services] Sending {'Content-Type': 'text/xml; charset="utf-8"', 'SOAPACTION': 'urn:schemas-upnp-org:service:AVTransport:1#GetPositionInfo'}, <?xml version="1.0" ?>
```

I tried to make a diff, but my python skills are not overall good 🤢 
I just found that the some block in "async def async_setup_entry" are missing in you implementation. But maybe you dont used them out of any good reason? I also think that this part is not the problem, but here are some examples

[def _stop_discovery(event: Event) -> None:](https://github.com/home-assistant/core/blob/8ce74e598d844d0b51aeb29983a2d7f114447c50/homeassistant/components/sonos/media_player.py#L175)

```python
    def _stop_discovery(event: Event) -> None:
        data = hass.data[DATA_SONOS]
        if data.discovery_thread:
            data.discovery_thread.stop()
            data.discovery_thread = None
        if data.hosts_heartbeat:
            data.hosts_heartbeat()
            data.hosts_heartbeat = None
```
[ if DATA_SONOS not in hass.data:](https://github.com/home-assistant/core/blob/8ce74e598d844d0b51aeb29983a2d7f114447c50/homeassistant/components/sonos/media_player.py#L164)
```python
 """Set up Sonos from a config entry."""
    if DATA_SONOS not in hass.data:
        hass.data[DATA_SONOS] = SonosData()
```
What currently puzzles me is that it works with the standard integration and pysonos, but not with the other discovery. I would like to help you more, but unfortunately this is too deep in python for me. :( 

Play music and sth. like that works without any problems ._.
![WhatsApp Image 2021-04-14 at 20 52 39](https://user-images.githubusercontent.com/47451170/114763818-87c3a080-9d63-11eb-84db-f689a2efde46.jpeg)
![chrome_7qaLxo4vOX](https://user-images.githubusercontent.com/47451170/114763903-9f9b2480-9d63-11eb-842c-d71283f51110.png)

If I can help you with any information getting this to work, please let me know.

Best regards

**Comment by AaronDavidSchneider** [comment]
Thanks for your comments! Yes indeed the lines you copied seem not to matter.

I will think about some debugging metrics that might help us to understand the issue.

Right now I am still confused that it works for me but not for you. And yes it's weird that it works with the core integration but not with Sonos alarm.

I will get back to you if I have an idea 😊

**Comment by AaronDavidSchneider** [comment]
Ok. So there is one first thing that we need to try. We need to get your alarm id and see if we can control the alarm from the core integration (there is a Service call that can update an alarm). This is how you can get the alarm id:

First install soco:

https://docs.python-soco.com/en/latest/getting_started.html#from-pypi-with-pip

I will give you a script for printing the alarm id soon.

**Comment by AaronDavidSchneider** [comment]
Hi,
I just found the bug. Apparently the integration was searching for the keyword `media_player` and not for `switch` in the yaml.
```
sonos_alarm:
   media_player:
      hosts:
        - 192.168.178.22
        - 192.168.178.29
        - 192.168.178.24
```
When there was nothing under `media_player` it continues to search for automatically discovered devices (which does work for me, but does not work for you).

So:
I created a PR #20 which changes back to `switch` instead of `media_player`.
This hopefully solves the problem.

Could you please test it? So first of all test if you use the keyword media_player and secondly try to change `media_player` in line 45 of the `switch.py` file to `switch`.

**Comment by Schmandre** [comment]
Hello,

the workaround to change `media_player` to `switch` in `switch.py` worked for me, discovery was now possible and works correct! 
![chrome_jILXaMVSEU](https://user-images.githubusercontent.com/47451170/114842688-61404c80-9dd9-11eb-8931-b570b493a877.png)
![chrome_bHaxRUDffK](https://user-images.githubusercontent.com/47451170/114842684-60a7b600-9dd9-11eb-8a6a-1cfa64f89123.png)

Thank you a LOT for your help. 

So your PR https://github.com/AaronDavidSchneider/SonosAlarm/pull/20 should fix the issue!

**Comment by AaronDavidSchneider** [comment]
Thank you a lot for this bug report and for reporting back to my questions! I will close this issue now!
