### ISSUE TITLE
pysonos mismatch with HA core leads to long boot times

### ISSUE THREAD

**Issue by Kugelfang666** [AaronDavidSchneider/SonosAlarm#2]
after updating to HA 0.108.X I started to encounter very long boot times. 

In the log it was found that the system tried to install 
```
Attempting install of pysonos==0.0.24
Attempting install of pysonos==0.0.25
```
After removing the SonosAlarm CC boot times immediately normalized.

On discord @ludeeus mentioned this in the context of this problem:

> https://github.com/hacs/integration/blob/master/tests/test_requirements.py 
> This is how I handle it for HACS, any dev can implemet the same logic for their CC

**Comment by AaronDavidSchneider** [comment]
Thanks for sharing! I will fix this asap.

I don't quite understand the file you shared. Is that supposed to run automatically by hacs?

**Comment by Kugelfang666** [comment]
> I don't quite understand the file you shared. Is that supposed to run automatically by hacs?

i "think" the idea was so show how one can automatically test against a version conflict in a CC vs the dependancies in HA core. but again its pure speculation :D

**Comment by ludeeus** [comment]
@AaronDavidSchneider That is run with `pytest` (among other tests) with each commit I do in HACS to ensure that HACS itself does not have any mismatch in requirements.
It only affects HACS, but can easily be copied and modified to _any_ repository.

**Comment by AaronDavidSchneider** [comment]
Thankyou for sharing your tests @ludeeus! I now include them in this repository as well. Seemed to work.

**Comment by amelchio** [comment]
Maybe you can just depend on `pysonos` (no version) and it will just keep working when no incompatible changes are introduced?

**Comment by AaronDavidSchneider** [comment]
> Maybe you can just depend on `pysonos` (no version) and it will just keep working when no incompatible changes are introduced?

If you say that there are not going to be breaking changes, then of course I can do that. In general I would say its better to pin the version and check if updating the dependency doesnt break the code.

**Comment by amelchio** [comment]
I'm not saying that. I am saying that you can pick between breaking for sure or only breaking on incompatible changes.

**Comment by AaronDavidSchneider** [comment]
Thats true indeed. Changed it.
