### ISSUE TITLE
entities not available

### ISSUE THREAD

**Issue by ghost** [AaronDavidSchneider/SonosAlarm#29]
Hello, 
I've set 3 Alarms in my Sonos system. All 3 Alarms are visible and functional in HA for a few minutes, then 2 Alarm entities disappear. I have tried to set up new Alarms in the Sonos app, no success. I've also reinstalled the custom integration under HACS with restart. It worked before several months, I think it started with the last update of the core or the supervisor.

HA is installed in a VMM on a Synology.
core-2021.4.6
supervisor-2021.04.0
SonosAlarm 1.3.1

**Comment by AaronDavidSchneider** [comment]
Hi,
thanks for your report! Do you have log entries?
Cheers
Aaron

**Comment by ghost** [comment]
2021-04-27 10:45:26 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.sonos_alarm_2272

**Comment by ghost** [comment]
So After several restarts the entities are available now for 35 minutes. I hope it will keep on working.

**Comment by AaronDavidSchneider** [comment]
That sounds really strange! If the error occurs again you could try to remove the integration and re-add it again (in the integrations pane of the UI).

**Comment by lancer73** [comment]
I have seen this too. I already re-added (and restarted in between), but it didn't help.

**Comment by ghost** [comment]
Yes the error is back after a few hours.

**Comment by AaronDavidSchneider** [comment]
Oh no... Could you try the open PR #28?
Just replace your files by the one that the PR provides.
Please let me know if that fixes the problem and/or if you need help setting it up 😊
Thanks in advance!

**Comment by AaronDavidSchneider** [comment]
Hi @pschyrembel258, @lancer73,
could you tell me if its possible that the error occurred once a sonos player has not been reachable by HomeAssistant (i.e. connection issues)?
I am still trying to reproduce the error but can't find your problem.

**Comment by lancer73** [comment]
> Hi @pschyrembel258, @lancer73,
> could you tell me if its possible that the error occurred once a sonos player has not been reachable by HomeAssistant (i.e. connection issues)?
> I am still trying to reproduce the error but can't find your problem.

All Sonos are wired with wifi turned off. As far as I know there haven't been any connection issues. So far it happened only on devices with multiple alarms (could be a statistical fluke) and all are stereo pairs. I rebooted yesterday and now on a device pair with 8 alarms set 4 have disappeared and on a device pair with 16 alarms 12 have disappeared. On two device pairs with one alarm each everything is OK. It looks like it increases with the number of alarms set.

**Comment by ghost** [comment]
I don't have stereopairs with alarms in my setup. My play 3 with multiple alarms is also wired.

**Comment by AaronDavidSchneider** [comment]
Hi @pschyrembel258, @lancer73,
could you please try https://github.com/home-assistant/core/pull/50719 and verify that the issue does not persist anymore? 
I would be happy for some feedback! 
Cheers!

**Comment by ghost** [comment]
How do I have to install this?

**Comment by AaronDavidSchneider** [comment]
You could either follow the developer docs: https://developers.home-assistant.io/docs/development_environment

Or you can simply drag the sonos folder from the fork of the PR and add it as a custom_component.

**Comment by lancer73** [comment]
Thanks for the update. I grabbed the sonos folder from the PR fork and put it in custom_components, but then the sonos component fails to load. Trying to re-add gives me a “failed to add config flow”. When I have more time available I’ll try with debug logs enabled.

**Comment by AaronDavidSchneider** [comment]
Hi, sorry for the wrong information. I thought it would be that easy to replace the sonos folder. But it looks like that is not possible. 
I think there seems to be no other option than to checkout the PR and run the development version of homeassistant on your local machine (see developer docs) if you want to try it.
