### ISSUE TITLE
time is not anymore available in the payload of the sonos_alarm

### ISSUE THREAD

**Issue by jebeke65** [AaronDavidSchneider/SonosAlarm#30]
![Screenshot 2021-04-29 at 11 41 37](https://user-images.githubusercontent.com/47870698/116531845-e64e5a00-a8df-11eb-8219-cb3fc1dfaf1c.png)

until recently, I could get the time for the Sonos Alarm.
now the retrieved Json does not show time anymore.

Any possibility to get the time of the alarm ?

**Comment by AaronDavidSchneider** [comment]
Hi,

thanks for your question. The time is definitely still part of the attributes of the switch!
Here is an example how I got the time from my alarm:
```
{{ states.switch.sonos_alarm_161.attributes.time }}
```

You should ensure that you are using the correct entity_id. You might also need to readd the integration and verify that you use the latest version of it.

**Comment by AaronDavidSchneider** [comment]
Hi, I hope that you were able to fix your problem.
Anyway, this custom component will be outdated and replaced by https://github.com/home-assistant/core/pull/50719 (hopefully) soon.
Feel free to test it!
