### ISSUE TITLE
Message from my log

### ISSUE THREAD

**Issue by yvansandoz** [AaronDavidSchneider/SonosAlarm#32]
The Sonos Alarm (sonos_alarm) integration is setting a connection_class when calling the 'register_discovery_flow()' method in its config flow. The connection class has been deprecated and will be removed in a future release of Home Assistant. If 'sonos_alarm' is a custom integration, please contact the author of that integration about this warning.

**Comment by AaronDavidSchneider** [comment]
Hi, sonos_alarm is depreciated. Please use the sonos integration instead.

**Comment by noiwid** [comment]
Hi, 
I noticed exactlly the same message with Sonos Integration :

```
Logger: homeassistant.helpers.config_entry_flow
Source: helpers/config_entry_flow.py:155
First occurred: 11:59:43 AM (1 occurrences)
Last logged: 11:59:43 AM

("The Sonos (sonos) integration is setting a connection_class when calling the 'register_discovery_flow()' method in its config flow. The connection class has been deprecated and will be removed in a future release of Home Assistant. If 'sonos' is a custom integration, please contact the author of that integration about this warning.",)
```

Any idea on how to fix it?

**Comment by AaronDavidSchneider** [comment]
Hi @noiwid, please reopen an issue with more details at the homeassistant core repo. Thanks
